---
name: Clojure Linting

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  clojure-linting:
    name: Clojure Linting
    runs-on: ubuntu-latest
    steps:
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: latest              # Clojure CLI based on tools.deps
          lein: latest                  # Leiningen
          boot: latest                  # Boot.clj
          bb: latest                    # Babashka
          clj-kondo: latest        # Clj-kondo
      - name: kondo lint
        run: clj-kondo --lint src test
      - name: eastwood lint
        run: lein eastwood
